# MySQL
#
development:
  adapter: mysql2
  host: 127.0.0.1
  database: srenvio_development
  username: root
  password: Benja0309
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: 127.0.0.1
  database: srenvio_test
  username: root
  password: Benja0309
  pool: 5
  timeout: 5000